title:              renderer86's blog
tagline:            renderer86
description:        renderer86's blog
url:                http://renderer86.github.io

author:
  name:             renderer86
  url:
  email:

# GitHub Pages / Jekyll configuration
baseurl:            ''
permalink:          /:title/
paginate:           5
paginate-path:      "/page:lang/page:num/"
defaults:
  -
    scope:
      path:         ''
    values:
      layout:       post

plugins:
    - jekyll-feed
